# SUPABASE_URL = "http://127.0.0.1:54321"
# SUPABASE_ADMIN_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"
# TEST_USER_EMAIL = "demo@example.com"
# TEST_USER_PASSWORD = "testuser"
# TEST_USER_ID = "75672178-19c8-420c-840b-13d03af1a056"

SUPABASE_URL = "https://hhqppcqltklzfpggdocb.supabase.co"
SUPABASE_ADMIN_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhocXBwY3FsdGtsemZwZ2dkb2NiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwMTM1NTgzOCwiZXhwIjoyMDE2OTMxODM4fQ.nwMZQwEGST0fNVATc6PAm_TaQwc95YcM2W1BLVj-9rU"
TEST_USER_EMAIL = "allison+cli_test@quotientai.co"
TEST_USER_PASSWORD = "Foobarbaz3lt0N"
TEST_USER_ID = "0ffea1d7-482b-4696-a9e6-c8fef8afa7f3"

TEST_INVALID_PASSWORD = "wrongpassword"
TEST_API_KEY_NAME = "testkeynamehere"
TEST_BAD_PROMPT_TEMPLATE = "badprompttemplate"
TEST_CREATE_PROMPT_TEMPLATE = "Customer question: {input_text}\n\nShakespearean styles: {context}\n\nAnswer as King Lear:"
