# .github/workflows/pytest.yml
name: Unit Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install poetry==1.6.1
        poetry config virtualenvs.create false \
          && poetry install --no-interaction --no-ansi --no-dev --no-cache \
          && rm -rf /root/.cache

    - name: Run PyTest
      run: |
        pytest
